# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/root";
      fsType = "ext4";
    };

#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/cf08bc12-afa4-4049-a126-b511976e0acb";
#      fsType = "ext3";
#    };

  swapDevices = [ ];

  nix.maxJobs = 4;
}
